interface IMoonlitDao {
  function AUTHOR_ADDRESS (  ) external view returns ( address );
  function AUTHOR_NAME (  ) external view returns ( string );
  function AUTHOR_ROLE (  ) external view returns ( bytes32 );
  function DEFAULT_ADMIN_ROLE (  ) external view returns ( bytes32 );
  function GENRE (  ) external view returns ( string );
  function IPFSLINK (  ) external view returns ( string );
  function MAX_PER_WALLET (  ) external view returns ( uint256 );
  function MINT_PRICE (  ) external view returns ( uint256 );
  function MOONLIT_FOUNDATION_ADDRESS (  ) external view returns ( address );
  function SUBTITLE (  ) external view returns ( string );
  function TITLE (  ) external view returns ( string );
  function addContributor ( address _contributor, uint256 _share ) external;
  function author (  ) external view returns ( uint256 share, uint256 shareInMatic, bool hasWithdrawnShare );
  function balanceOf ( address account, uint256 id ) external view returns ( uint256 );
  function balanceOfBatch ( address[] accounts, uint256[] ids ) external view returns ( uint256[] );
  function claimGenesisEditionNFT ( address account ) external;
  function claimRefund (  ) external;
  function contributorIndex (  ) external view returns ( uint8 );
  function contributors ( uint256 ) external view returns ( address shareRecipient, uint256 share, uint256 shareInMatic, bool hasWithdrawnShare );
  function currentEdition (  ) external view returns ( uint256 );
  function currentEditionMax (  ) external view returns ( uint256 );
  function currentEditionMintPrice (  ) external view returns ( uint256 );
  function deposit ( uint256 _amount ) external;
  function enableNextEdition ( uint256 _maxNftAmountOfNewEdition, uint256 _newEditionMintPrice ) external;
  function enableRefund (  ) external;
  function exists ( uint256 id ) external view returns ( bool );
  function fundedAmount (  ) external view returns ( uint256 );
  function getRoleAdmin ( bytes32 role ) external view returns ( bytes32 );
  function getRoleMember ( bytes32 role, uint256 index ) external view returns ( address );
  function getRoleMemberCount ( bytes32 role ) external view returns ( uint256 );
  function grantRole ( bytes32 role, address account ) external;
  function hasRole ( bytes32 role, address account ) external view returns ( bool );
  function investingFinished (  ) external view returns ( bool );
  function investments ( address ) external view returns ( uint256 );
  function isApprovedForAll ( address account, address operator ) external view returns ( bool );
  function mint ( address account, uint256 _amount ) external;
  function refundEnabled (  ) external view returns ( bool );
  function renounceRole ( bytes32 role, address account ) external;
  function revokeRole ( bytes32 role, address account ) external;
  function safeBatchTransferFrom ( address from, address to, uint256[] ids, uint256[] amounts, bytes data ) external;
  function safeTransferFrom ( address from, address to, uint256 id, uint256 amount, bytes data ) external;
  function setApprovalForAll ( address operator, bool approved ) external;
  function setURI ( string newuri ) external;
  function shareSentToMoonlit (  ) external view returns ( bool );
  function supportsInterface ( bytes4 interfaceId ) external view returns ( bool );
  function totalSharePercentage (  ) external view returns ( uint256 );
  function totalSupply ( uint256 id ) external view returns ( uint256 );
  function uri ( uint256 ) external view returns ( string );
  function withdrawAll (  ) external;
  function withdrawShareAuthor ( address _to ) external;
  function withdrawShareContributor ( address _to ) external;
}
